[[contributing-to-docs-tools-and-setup]]
= Install and set up the tools and software
:icons:
:toc: macro
:toc-title:
:toclevels: 1
:linkattrs:
:description: How to set up and install the tools to contribute

toc::[]

== Create a GitHub account
Before you can contribute to OpenShift documentation, you must
https://www.github.com/join[sign up for a GitHub account].

== 创建GitHub账号
贡献Openshift汉化文档项目前，
https://www.github.com/join[先申请个GitHub账号吧].

== Set up authentication
When you have your account set up, follow the instructions to
https://help.github.com/articles/generating-ssh-keys/[generate and set up SSH
keys on GitHub] for proper authentication between your workstation and GitHub.

Confirm authentication is working correctly with the following command:

----
$ ssh -T git@github.com
----

== 设置认证
当您设置帐户时，请按照 https://help.github.com/articles/generating-ssh-keys/[在GitHub上生成并设置SSH密钥]的说明，
在工作站和GitHub之间进行正确的身份验证。

使用以下命令确认身份验证是否正常工作：

----
$ ssh -T git@github.com
----

== Fork and clone the OpenShift documentation repository
You must fork and set up the OpenShift documentation repository on your
workstation so that you can create PRs and contribute. These steps only need to
be performed during initial setup.

1. Fork the https://github.com/openshift/openshift-docs repository into your
GitHub account from the GitHub UI. You can do this by clicking on *Fork* in the
upper right-hand corner.

2. On your workstation, clone the forked repository on your workstation with the
following command. Be sure to change into the directory where you want to clone,
and replace _<user_name>_ with your actual GitHub username.
+
----
$ git clone git@github.com:user_name/openshift-docs.git
----

3. From your local repository you just cloned, add an upstream pointer back to
the OpenShift's remote repository, in this case _openshift-docs_.
+
----
$ git remote add upstream git@github.com:openshift/openshift-docs.git
----

This ensures that you are tracking the remote repository to keep your local
repository in sync with it.

== Fork 和 clone此项目
必须在您的机器上fork和设置此项目，以便您可以创建PR和贡献。 这些步骤只需要
一开始设置一次就OK了。

1. 通过GitHub的界面Fork此项目 https://github.com/xiaoping378/openshift-docs
 就是点击右上角的`Fork`按钮

2. 克隆你刚才fork出来的项目到本地，自行替换_<user_name>_部分.
+
----
$ git clone git@github.com:user_name/openshift-docs.git
----

3. 进入_openshift-docs_目录，添加远程上游.
+
----
$ git remote add upstream git@github.com:xiaoping378/openshift-docs.git
----

这确保您正在跟踪远程代码仓，以保证您的本地代码与它同步。

== Install AsciiBinder and dependencies
When you have the documentation repository cloned and set up, you are ready to
install the software and tools you will use to create the content. All OpenShift
documentation is created in AsciiDoc, and is processed with http://asciibinder.org[AsciiBinder],
which is an http://asciidoctor.org/[AsciiDoctor]-based docs management system.

You can work on a topic file in an editing environment that automatically
processes and updates the rendered HTML.

== 安装AsciiBinder
克隆并设置此项目后，接下来准备好安装将用于生成html内容的软件和工具。
所有OpenShift文档在AsciiDoc中创建，并由 http://asciibinder.org[AsciiBinder]处理，
这是一个基于 http://asciidoctor.org/[AsciiDoctor]的文档管理系统。

你可以做到实时编辑并预览web页面

=== What you need
The following are minimum requirements to set up a live editing environment:

* A bash shell environment (Linux and OS X include a bash shell environment out
of the box, but if you are on Windows you can use http://cygwin.com/[Cygwin])
* https://www.ruby-lang.org/en/[Ruby]
* http://www.git-scm.com/[Git]
* A web browser (Firefox, Chrome, or Safari) with the
http://livereload.com/[LiveReload] extension installed

=== 需要什么
准备汉化开发环境的最小依赖:

* 一个bash终端环境(Linux和OS X已经自带了, windows上话可以使用 http://cygwin.com/[Cygwin]，或者开虚机)
* https://www.ruby-lang.org/en/[Ruby]
* http://www.git-scm.com/[Git]
* 浏览器上最好安装此插件 http://livereload.com/[LiveReload]， 不想装的话就手动F5吧

=== Install the required software dependencies on a Linux system
The following instructions describe how to install all the required tools to do
live content editing on a Fedora Linux system.

1. Install the _RubyGems_ package with `yum install rubygems`
2. Install _Ruby_ development packages with `yum install ruby-devel`
3. Install _gcc_ with `yum install gcc-c++`
4. Install _redhat-rpm-config_ with `yum install redhat-rpm-config`
5. Install _make_ with `yum install make`
6. Install the _ascii_binder_ gem with `gem install ascii_binder`

NOTE: If you already have AsciiBinder installed, you may be due for an update. These directions assume that you are using AsciiBinder 0.0.8 or newer. To check and update if necessary, simply run `gem update ascii_binder`. Note that you may need root permissions.

=== 安装依赖软件
以下说明介绍如何安装所有必需的工具，以便在Fedora Linux系统上进行实时内容编辑。

1. 安装 _RubyGems_ `yum install rubygems`
2. 安装 _Ruby_ 开发包 `yum install ruby-devel`
3. 安装 _gcc_  `yum install gcc-c++`
4. 安装 _redhat-rpm-config_ `yum install redhat-rpm-config`
5. 安装 _make_ `yum install make`
6. 安装_ascii_binder_  `gem install ascii_binder`

NOTE: 如果已经安装了AsciiBinder， 确保其版本大于0.0.8， 简单的跑下`gem update ascii_binder`，是肯定OK的

=== 剩下的就简单了，略翻。。。

1. 通过`asciibinder build`编译
2. 通过`asciibinder watch`实时查看编译出来的HTML文档

=== Initial setup
After you have confirmed that you meet the minimum system requirements, or if
you are on a Linux system you have installed the
link:#install-the-required-software-dependencies-on-a-linux-system[required
software dependencies], you can perform the initial setup.

[NOTE]
.ditaa Support
====
https://github.com/stathissideris/ditaa[ditaa] requires $JAVA_HOME be set, which requires a JDK
installed (try e.g. `yum install java-1.8.0-openjdk-devel` and `export
JAVA_HOME=/usr/lib/jvm/java-1.8.0`).
====

=== How to use LiveReload
With the initial setup complete, you are ready to use LiveReload to edit your
content.

1. From the `openshift-docs` directory, run an initial build:
+
----
$ cd openshift-docs
$ asciibinder build
----
2. Open the generated HTML file in your web browser. This will be located in the
`openshift-docs/_preview/<distro>/<branch>` directory, with the same path and
filename as the original `.adoc` file you edited, only it will be with the
`.html` extension.
3. Run the `watch` utility:
+
----
$ asciibinder watch
----
+
[TIP]
This utility will run in the terminal where you started it, so you should leave
it running and open new terminal windows for other tasks.

4. In your browser, enable the LiveReload plug-in in the same tab where the
preview file is open; the icon should change color once activated. The following
message will also display in your terminal window:
+
----
[1] guard(main)> 17:29:22 - INFO - Browser connected.
----

With this setup, a rebuild is automatically generated each time you make a change
to the source `.adoc` file, and is immediately viewable in the corresponding
`.html` file.

=== Clean up
The `.gitignore` file is set up to prevent anything under the `_preview` and
`_package` directories from being committed. However, you can reset the
environment manually by running:

----
$ asciibinder clean
----

== Next steps
With the repository and tools set up on your workstation, you can now either
edit existing content or create new topics.

* link:doc_guidelines.adoc[Review the documentation guidelines] to understand
some basic guidelines to keep things consistent across our content.
* link:create_or_edit_content.adoc[Create a local working branch] on your
workstation to edit existing topics or create new topics.
